# Generated by Django 5.1.6 on 2025-02-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tilte',
            new_name='title',
        ),
    ]
